### ISSUE TITLE
Rendering is off in PR reviews

### ISSUE THREAD

**Issue by oscarlofwenhamn** [N1ck/gifs-for-github#70] opened 2024-01-08 13:28 UTC
When trying to add a gif to a PR review, the following is rendered:

Initial state:
![image](https://github.com/N1ck/gifs-for-github/assets/44643697/be01cfe3-13ac-4245-ac1f-70afbb0eefd2)

After clicking GIF button:
![image](https://github.com/N1ck/gifs-for-github/assets/44643697/1c8900b0-add3-41c7-9dac-0ee56221c832)

Browser version: Version 120.0.6099.199 (Official Build) (arm64)
Extension version: 24.1.6.1944

Possibly related to the same underlying problem as #68?

**Comment by N1ck** [comment] 2024-01-08 21:59
Hey, thanks for submitting an issue!

I can't seem to reproduce this unfortunately, but I have a hunch, and made a PR that should hopefully fix this for you here: https://github.com/N1ck/gifs-for-github/pull/71

I have submitted the updated extension for review, it should be version number `24.1.8` when it's active. If you could try again when it's updated and let me know that would be great.

<img src="https://media1.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>

**Comment by oscarlofwenhamn** [comment] 2024-01-09 08:39
Thanks for the quick and friendly response! 

It's still broken in my end unfortunately. Works as expected for gifs in regular comments, but for PR reviews it looks as pictured above. Strangely enough, in PR *comments* it works as expected, only when adding the final verdict things are off.

I noticed similar behaviour when narrowing the screen to <1112 pixels, i.e. when the GIF-button gets out of bounds, maybe that's easier to reproduce?

Width = 1112px
![image](https://github.com/N1ck/gifs-for-github/assets/44643697/948a1058-6dcf-417e-8da3-ca8f0df53be0)

Width < 1112px (expanded)
![image](https://github.com/N1ck/gifs-for-github/assets/44643697/ddc8af69-1081-4aef-8f23-6adad0986133)

Width < 1112px (minimized)
![image](https://github.com/N1ck/gifs-for-github/assets/44643697/59de59da-cd46-466f-b6b6-c1832439fe67)

No sweat if this isn't a prioritised bug, workarounds are available after all (e.g. finding the perfect gif in a regular comment and then copying the link), just happy to report a finding for my legitimately no. 1 most used Chrome extension. 👏 

<img src="https://media3.giphy.com/media/iGvsSyH0XG8xZH3hjE/giphy.gif"/>

**Comment by miluoshi** [comment] 2024-01-10 10:57
For me it is not fixed on `24.1.8` regardless of the screen width. It is worth noting that I'm also using [Refined Github extension](https://github.com/refined-github/refined-github), but it is not fixed even if I disable the extension.

Refined Github on:
![image](https://github.com/N1ck/gifs-for-github/assets/1130547/1e4a1872-dcf2-4266-b6f3-a885d8c86a72)

Refined Github off, default state:
![image](https://github.com/N1ck/gifs-for-github/assets/1130547/515f37e0-f9a1-4f80-8d6c-2c912843f233)

Refined Github off, opened state:
![image](https://github.com/N1ck/gifs-for-github/assets/1130547/bfb5e7a5-1afd-40c5-967b-a769fea8324f)

**Comment by nikolaik** [comment] 2024-01-15 14:47
I've hit this too, but can work around it if I increase the vertical height of the comment textarea. Not sure why that is relevant though

**Comment by N1ck** [comment] 2024-01-16 22:38
Thank you for all of the screenshots and helping debug 🎉 

<img src="https://media4.giphy.com/media/RipfZWzjUDH25euMpM/giphy.gif"/>


Sorry I haven't had a lot of time to look at this, after further digging I was finally able to reproduce it.

It wasn't happening for me because I had my scroll settings set to:
<img width="308" alt="image" src="https://github.com/N1ck/gifs-for-github/assets/1018141/b22c2b54-216d-4387-968c-f1cbe7e998d5">

But when changing it to "Always" I could reliably replicate it.

I think I have a fix now which should be in version `24.1.16` 

<img src="https://media3.giphy.com/media/xT5P0WEiP5n4WMGUG4/giphy.gif"/>

**Comment by N1ck** [comment] 2024-01-17 23:42
GitHub has made another, unrelated change to their layout which has caused it to break again 😭 I have already fixed it but have to wait for another approval before it's live.

<img src="https://media4.giphy.com/media/OPU6wzx8JrHna/giphy.gif"/>

**Comment by oscarlofwenhamn** [comment] 2024-01-18 08:10
<img src="https://media4.giphy.com/media/3Lgbe3PW6oR9yEHpOn/giphy.gif"/>

**Comment by N1ck** [comment] 2024-01-21 08:10
The latest version `24.1.18` should resolve this issue. Sorry it took so long, it took over 2 days to be reviewed 😢 


<img src="https://media4.giphy.com/media/3orif3zV7e8oYtuPjW/giphy.gif"/>

**Closed by N1ck** 2024-01-21 08:10 UTC
Labels: bug

**Comment by oscarlofwenhamn** [comment] 2024-01-22 10:33
Confirmed!
![image](https://github.com/N1ck/gifs-for-github/assets/44643697/dc8799a5-fb42-4a81-b89e-b8119ecd1a5a)

<img src="https://media4.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif"/>

**Comment by nikolaik** [comment] 2024-01-22 10:37
<img src="https://media0.giphy.com/media/j73NQrUd28QHGMJpQH/giphy.gif"/>
